# Generated by Django 2.2.6 on 2019-11-02 20:51

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('target_gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('B', 'Both')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BodyCosmetic',
            fields=[
                ('cosmetic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cosmetics.Cosmetic')),
                ('skin_type', models.CharField(choices=[('Oi', 'Oily skin'), ('Dr', 'Dry skin'), ('Se', 'Sensitive skin')], max_length=2)),
                ('properties', models.CharField(max_length=100)),
            ],
            bases=('cosmetics.cosmetic', models.Model),
        ),
        migrations.CreateModel(
            name='FaceCosmetic',
            fields=[
                ('cosmetic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cosmetics.Cosmetic')),
                ('skin_type', models.CharField(choices=[('Oi', 'Oily skin'), ('Dr', 'Dry skin'), ('Se', 'Sensitive skin'), ('Co', 'Combination skin'), ('No', 'Normal'), ('Ca', 'Capillaries')], max_length=2)),
                ('time_of_day', models.CharField(choices=[('D', 'Day'), ('N', 'Night')], max_length=1)),
                ('properties', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Moisturizing'), ('R', 'Reviviscent'), ('A', 'Antiaging'), ('C', 'Cleansing'), ('S', 'Sunscreen')], max_length=1)),
            ],
            bases=('cosmetics.cosmetic', models.Model),
        ),
        migrations.CreateModel(
            name='HairCosmetic',
            fields=[
                ('cosmetic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cosmetics.Cosmetic')),
                ('hair_type', models.CharField(choices=[('H', 'High Porosity'), ('L', 'Low Porosity'), ('M', 'Medium Porosity'), ('A', 'All types')], max_length=1)),
                ('hair_problem', models.CharField(choices=[('H', 'Weak hair'), ('C', 'Colored hair'), ('D', 'Dandruff hair'), ('O', 'Oily hair'), ('A', 'All hair')], max_length=1)),
                ('properties', models.CharField(max_length=100)),
            ],
            bases=('cosmetics.cosmetic', models.Model),
        ),
    ]
