# Generated by Django 2.2.7 on 2019-11-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('website', models.URLField()),
                ('country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('target_gender', models.CharField(max_length=1)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CosmeticProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('ingredient_type', models.CharField(max_length=3)),
                ('natural', models.BooleanField()),
                ('hypoallergenic', models.BooleanField()),
                ('verified', models.BooleanField(default=False)),
                ('cosmetic', models.ManyToManyField(to='cosmetics.Cosmetic')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cosmetics.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='HandsCosmetic',
            fields=[
                ('cosmetic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cosmetics.Cosmetic')),
                ('skin_type', models.CharField(max_length=2)),
                ('properties', models.ManyToManyField(to='cosmetics.CosmeticProperties')),
            ],
            bases=('cosmetics.cosmetic',),
        ),
        migrations.CreateModel(
            name='HairCosmetic',
            fields=[
                ('cosmetic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cosmetics.Cosmetic')),
                ('hair_type', models.CharField(max_length=1)),
                ('hair_problem', models.CharField(max_length=1)),
                ('properties', models.ManyToManyField(to='cosmetics.CosmeticProperties')),
            ],
            bases=('cosmetics.cosmetic',),
        ),
        migrations.CreateModel(
            name='FeetCosmetic',
            fields=[
                ('cosmetic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cosmetics.Cosmetic')),
                ('skin_type', models.CharField(max_length=2)),
                ('properties', models.ManyToManyField(to='cosmetics.CosmeticProperties')),
            ],
            bases=('cosmetics.cosmetic',),
        ),
        migrations.CreateModel(
            name='FaceCosmetic',
            fields=[
                ('cosmetic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cosmetics.Cosmetic')),
                ('skin_type', models.CharField(max_length=2)),
                ('time_of_day', models.CharField(max_length=1)),
                ('properties', models.ManyToManyField(to='cosmetics.CosmeticProperties')),
            ],
            bases=('cosmetics.cosmetic',),
        ),
        migrations.CreateModel(
            name='BodyCosmetic',
            fields=[
                ('cosmetic_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cosmetics.Cosmetic')),
                ('skin_type', models.CharField(max_length=2)),
                ('properties', models.ManyToManyField(to='cosmetics.CosmeticProperties')),
            ],
            bases=('cosmetics.cosmetic',),
        ),
    ]
