# Generated by Django 2.2.7 on 2019-11-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='main_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cosmetic',
            field=models.ManyToManyField(blank=True, null=True, to='cosmetics.Cosmetic'),
        ),
        migrations.AlterField(
            model_name='ingredientnames',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
