# Generated by Django 2.2.9 on 2019-12-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodycosmetic',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='facecosmetic',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='feetcosmetic',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='haircosmetic',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='handscosmetic',
            name='properties',
        ),
        migrations.AddField(
            model_name='cosmetic',
            name='properties',
            field=models.ManyToManyField(to='cosmetics.CosmeticProperties'),
        ),
    ]
