# Generated by Django 2.2.7 on 2019-12-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_auto_20191128_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientNames',
            new_name='IngredientName',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cosmetic',
            field=models.ManyToManyField(blank=True, to='cosmetics.Cosmetic'),
        ),
    ]
