# Generated by Django 2.2.7 on 2019-12-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_auto_20191205_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodycosmetic',
            name='skin_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cosmetic',
            name='target_gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='facecosmetic',
            name='skin_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facecosmetic',
            name='time_of_day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='feetcosmetic',
            name='skin_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='haircosmetic',
            name='hair_problem',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='haircosmetic',
            name='hair_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='handscosmetic',
            name='skin_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(max_length=50),
        ),
    ]
